name: flutter_application_1
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.2
  cloud_firestore: ^4.15.2
  flutter_masked_text2: ^0.9.1
  image_picker: ^1.0.7
  share_plus: ^7.2.1
  cached_network_image: ^3.3.1
  screenshot: ^3.0.0 # Update to the latest compatible version
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  font_awesome_flutter: ^10.7.0
  firebase_auth: ^4.17.2
  google_sign_in: ^6.1.6
  english_words: ^4.0.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/google_logo.png
    - assets/povo_ninja.jpg
    - assets/smartwork_logo.png
    - assets/povo_ninja.jpg