// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9or2iTmdnIam0tXB7lMemb29aDPaQDKQ',
    appId: '1:14548167982:web:f354c9e54d83fbc420debf',
    messagingSenderId: '14548167982',
    projectId: 'flutter-1-6face',
    authDomain: 'flutter-1-6face.firebaseapp.com',
    storageBucket: 'flutter-1-6face.firebasestorage.app',
    measurementId: 'G-9GTZFFVT7C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJWHY3Bw2av4XVIm0A2cwIkocZQdlc0V4',
    appId: '1:14548167982:android:d38d82c7e399409a20debf',
    messagingSenderId: '14548167982',
    projectId: 'flutter-1-6face',
    storageBucket: 'flutter-1-6face.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3J0bq1aZFEp_sptFiZKwmTIyBAhL6nag',
    appId: '1:14548167982:ios:05a5703f0ef53f4820debf',
    messagingSenderId: '14548167982',
    projectId: 'flutter-1-6face',
    storageBucket: 'flutter-1-6face.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3J0bq1aZFEp_sptFiZKwmTIyBAhL6nag',
    appId: '1:14548167982:ios:05a5703f0ef53f4820debf',
    messagingSenderId: '14548167982',
    projectId: 'flutter-1-6face',
    storageBucket: 'flutter-1-6face.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9or2iTmdnIam0tXB7lMemb29aDPaQDKQ',
    appId: '1:14548167982:web:bd7b78a10a058e2820debf',
    messagingSenderId: '14548167982',
    projectId: 'flutter-1-6face',
    authDomain: 'flutter-1-6face.firebaseapp.com',
    storageBucket: 'flutter-1-6face.firebasestorage.app',
    measurementId: 'G-FRS4M3HMYB',
  );
}
